version: '3.7'
services:
  proxy-sage:
    image: nginx
    container_name: proxy_sage
    networks:
      - frontend
    volumes:
     - /riptalon/Appdata/recipesage/nginx-sage/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sage_static
      - sage_api
      - sage_pushpin
    restart: unless-stopped
    
  sage_static:
    image: julianpoy/recipesage-selfhost:static-latest
    container_name: sage_static
    networks:
      - frontend
    restart: unless-stopped

  sage_api:
    image: julianpoy/recipesage-selfhost:api-latest
    container_name: sage_api
    networks:
      - backend
      - frontend
    depends_on:
      - sage_postgres
      - sage_elastic
      - sage_pushpin
      - sage_browserless
    command: /app/www
    environment:
      - AWS_ACCESS_KEY_ID=recipesage23
      - AWS_SECRET_ACCESS_KEY=recipesage_selfhost23
      - AWS_REGION=us-west-2
      - AWS_BUCKET=recipesage-selfhost
      - AWS_ENDPOINT=http://sage_minio:9000/ # Needed for minio, remove for s3 - should be the internal container address to minio
      - AWS_S3_PUBLIC_PATH=/minio/recipesage-selfhost/ # Needed for minio, remove for s3 - should be a public facing address/path directed to minio (by default nginx proxy handles)
      - AWS_S3_FORCE_PATH_STYLE=true # Needed for minio, remove for s3
      - AWS_S3_SIGNATURE_VERSION=v4 # Needed for minio, remove for s3
      - NODE_ENV=selfhost
      - VERBOSE=false
      - VERSION=selfhost
      - POSTGRES_DB=recipesage_selfhost23
      - POSTGRES_USER=recipesage_selfhost23
      - POSTGRES_PASSWORD=recipesage_selfhost23
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=sage_postgres
      - POSTGRES_SSL=false
      - POSTGRES_LOGGING=false
      - GCM_KEYPAIR
      - SENTRY_DSN
      - GRAYLOG_HOST=localhost
      - GRAYLOG_PORT
      - GRIP_URL=http://sage_pushpin:5561/
      - GRIP_KEY=changeme
      - ELASTIC_ENABLE=true
      - ELASTIC_IDX_PREFIX=rs_selfhost_
      - ELASTIC_CONN=http://sage_elastic:recipesage_selfhost@elasticsearch:9200
      - ELASTIC_PASSWORD=recipesage_selfhost
      - STRIPE_SK
      - STRIPE_WEBHOOK_SECRET
      - BROWSERLESS_HOST=sage_browserless
      - BROWSERLESS_PORT=3000
      - INGREDIENT_INSTRUCTION_CLASSIFIER_URL=http://sage_ingredient-instruction-classifier:3000/
    restart: unless-stopped

  sage_elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: sage_elastic
    networks:
      - frontend
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=recipesage_selfhost223
    volumes:
      - /riptalon/Appdata/recipesage/elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped

  sage_pushpin:
    image: fanout/pushpin:1.27.0
    container_name: sage_pushpin
    networks:
      - frontend
    environment:
      - target=sage_api:3000
    restart: unless-stopped

  sage_postgres:
    image: postgres
    container_name: sage_postgres
    networks:
      - backend
    environment:
      - POSTGRES_DB=recipesage_selfhost23
      - POSTGRES_USER=recipesage_selfhost23
      - POSTGRES_PASSWORD=recipesage_selfhost23
    volumes:
      - /riptalon/Appdata/recipesage/postgresdb:/var/lib/postgresql/data
    restart: unless-stopped

  sage_browserless:
    image: browserless/chrome:1.28.0-chrome-stable
    container_name: sage_browserless
    networks:
      - frontend
    environment:
      - MAX_CONCURRENT_SESSIONS=3
      - MAX_QUEUE_LENGTH=10
    restart: unless-stopped

  sage_ingredient-instruction-classifier:
    image: julianpoy/ingredient-instruction-classifier:latest
    container_name: sage_ingredient-instruction-classifier
    networks:
      - frontend
    environment:
      - SENTENCE_EMBEDDING_BATCH_SIZE=200
      - PREDICTION_CONCURRENCY=4
    restart: unless-stopped

  sage_minio:
    image: minio/minio
    container_name: sage_minio
    networks:
      - frontend
    environment:
      - MINIO_ACCESS_KEY=recipesage23
      - MINIO_SECRET_KEY=recipesage_selfhost23
    volumes:
      - /riptalon/Appdata/recipesage/minio:/data
    command: server /data
    restart: unless-stopped
    
  sage_mc:
    image: minio/mc
    container_name: sage_mc
    networks:
      - frontend
    depends_on:
      - sage_minio
    entrypoint: sh -c
    command: >
      "
      /usr/bin/mc config host add myminio http://sage_minio:9000 recipesage23 recipesage_selfhost23;
      /usr/bin/mc mb myminio/recipesage-selfhost;
      /usr/bin/mc policy set public myminio/recipesage-selfhost;
      exit 0;
      "

networks:
  frontend:
    external: true
  backend:
    external: true
