version: '3.7'
services:
  proxy-sage:
    image: nginx
    container_name: proxy-sage
    networks:
      - frontend
      - backend
    volumes:
     - /riptalon/Appdata/recipesage/nginx-sage/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 83:80
    depends_on:
      - static
      - api
      - pushpin
    restart: unless-stopped
    
  static:
    image: julianpoy/recipesage-selfhost:static-latest
    container_name: static
    networks:
      - frontend
      - backend
    restart: unless-stopped

  api:
    image: julianpoy/recipesage-selfhost:api-latest
    container_name: api
    networks:
      - backend
      - frontend
    depends_on:
      - sage_postgres
      - elasticsearch
      - pushpin
      - browserless
    command: /app/www
    environment:
      - AWS_ACCESS_KEY_ID=recipesage23
      - AWS_SECRET_ACCESS_KEY=recipesage_selfhost23
      - AWS_REGION=us-west-2
      - AWS_BUCKET=recipesage-selfhost
      - AWS_ENDPOINT=http://minio:9100/ # Needed for minio, remove for s3 - should be the internal container address to minio
      - AWS_S3_PUBLIC_PATH=/minio/recipesage-selfhost/ # Needed for minio, remove for s3 - should be a public facing address/path directed to minio (by default nginx proxy handles)
      - AWS_S3_FORCE_PATH_STYLE=true # Needed for minio, remove for s3
      - AWS_S3_SIGNATURE_VERSION=v4 # Needed for minio, remove for s3
      - NODE_ENV=selfhost
      - VERBOSE=false
      - VERSION=selfhost
      - POSTGRES_DB=recipesage_selfhost23
      - POSTGRES_USER=recipesage_selfhost23
      - POSTGRES_PASSWORD=recipesage_selfhost23
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=sage_postgres
      - POSTGRES_SSL=false
      - POSTGRES_LOGGING=false
      - GCM_KEYPAIR
      - SENTRY_DSN
      - GRAYLOG_HOST=localhost
      - GRAYLOG_PORT
      - GRIP_URL=http://pushpin:5561/
      - GRIP_KEY=changeme
      - ELASTIC_ENABLE=true
      - ELASTIC_IDX_PREFIX=rs_selfhost_
      - ELASTIC_CONN=http://elastic:recipesage_selfhost@elasticsearch:9200
      - ELASTIC_PASSWORD=recipesage_selfhost
      - STRIPE_SK
      - STRIPE_WEBHOOK_SECRET
      - BROWSERLESS_HOST=browserless
      - BROWSERLESS_PORT=3100
      - INGREDIENT_INSTRUCTION_CLASSIFIER_URL=http://ingredient-instruction-classifier:3100/
    ports:
      - '3100:3000'
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elastic
    networks:
      - frontend
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=recipesage_selfhost223
    volumes:
      - /riptalon/Appdata/recipesage/elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped

  pushpin:
    image: fanout/pushpin:1.27.0
    container_name: pushpin
    networks:
      - frontend
    environment:
      - target=api:3100
    ports:
      - '7999:7999'
    restart: unless-stopped

  sage_postgres:
    image: postgres
    container_name: sage_postgres
    networks:
      - backend
    environment:
      - POSTGRES_DB=recipesage_selfhost23
      - POSTGRES_USER=recipesage_selfhost23
      - POSTGRES_PASSWORD=recipesage_selfhost23
    volumes:
      - /riptalon/Appdata/recipesage/postgresdb:/var/lib/postgresql/data
    restart: unless-stopped

  browserless:
    image: browserless/chrome:1.28.0-chrome-stable
    container_name: browserless
    networks:
      - frontend
    environment:
      - MAX_CONCURRENT_SESSIONS=3
      - MAX_QUEUE_LENGTH=10
    restart: unless-stopped

  ingredient-instruction-classifier:
    image: julianpoy/ingredient-instruction-classifier:latest
    container_name: ingredient-instruction-classifier
    networks:
      - frontend
    environment:
      - SENTENCE_EMBEDDING_BATCH_SIZE=200
      - PREDICTION_CONCURRENCY=4
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    networks:
      - frontend
    environment:
      - MINIO_ACCESS_KEY=recipesage23
      - MINIO_SECRET_KEY=recipesage_selfhost23
    volumes:
      - /riptalon/Appdata/recipesage/minio:/data
    ports:
      - '9100:9000'
    command: server /data
    restart: unless-stopped
    
  create-minio-buckets:
    image: minio/mc
    container_name: mc
    networks:
      - frontend
    depends_on:
      - minio
    entrypoint: sh -c
    command: >
      "
      /usr/bin/mc config host add myminio http://minio:9100 recipesage23 recipesage_selfhost23;
      /usr/bin/mc mb myminio/recipesage-selfhost;
      /usr/bin/mc policy set public myminio/recipesage-selfhost;
      exit 0;
      "

networks:
  frontend:
    external: true
  backend:
    external: true
